/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyCourseCodeRouteImport } from './routes/study.$courseCode'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCourseCodeRoute = StudyCourseCodeRouteImport.update({
  id: '/$courseCode',
  path: '/$courseCode',
  getParentRoute: () => StudyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/home': typeof HomeRoute
  '/study': typeof StudyRouteWithChildren
  '/study/$courseCode': typeof StudyCourseCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/home': typeof HomeRoute
  '/study': typeof StudyRouteWithChildren
  '/study/$courseCode': typeof StudyCourseCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/home': typeof HomeRoute
  '/study': typeof StudyRouteWithChildren
  '/study/$courseCode': typeof StudyCourseCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exam' | '/home' | '/study' | '/study/$courseCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam' | '/home' | '/study' | '/study/$courseCode'
  id: '__root__' | '/' | '/exam' | '/home' | '/study' | '/study/$courseCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRoute
  HomeRoute: typeof HomeRoute
  StudyRoute: typeof StudyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$courseCode': {
      id: '/study/$courseCode'
      path: '/$courseCode'
      fullPath: '/study/$courseCode'
      preLoaderRoute: typeof StudyCourseCodeRouteImport
      parentRoute: typeof StudyRoute
    }
  }
}

interface StudyRouteChildren {
  StudyCourseCodeRoute: typeof StudyCourseCodeRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyCourseCodeRoute: StudyCourseCodeRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRoute,
  HomeRoute: HomeRoute,
  StudyRoute: StudyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
