/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyCourseCodeRouteImport } from './routes/study.$courseCode'
import { Route as SessionCourseCodeRouteImport } from './routes/session.$courseCode'
import { Route as ResultsCourseCodeRouteImport } from './routes/results.$courseCode'
import { Route as ExamCourseCodeRouteImport } from './routes/exam.$courseCode'
import { Route as ExamCourseCodeSessionRouteImport } from './routes/exam.$courseCode.session'
import { Route as ExamCourseCodeResultsRouteImport } from './routes/exam.$courseCode.results'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCourseCodeRoute = StudyCourseCodeRouteImport.update({
  id: '/$courseCode',
  path: '/$courseCode',
  getParentRoute: () => StudyRoute,
} as any)
const SessionCourseCodeRoute = SessionCourseCodeRouteImport.update({
  id: '/session/$courseCode',
  path: '/session/$courseCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsCourseCodeRoute = ResultsCourseCodeRouteImport.update({
  id: '/results/$courseCode',
  path: '/results/$courseCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamCourseCodeRoute = ExamCourseCodeRouteImport.update({
  id: '/$courseCode',
  path: '/$courseCode',
  getParentRoute: () => ExamRoute,
} as any)
const ExamCourseCodeSessionRoute = ExamCourseCodeSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ExamCourseCodeRoute,
} as any)
const ExamCourseCodeResultsRoute = ExamCourseCodeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ExamCourseCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/exam': typeof ExamRouteWithChildren
  '/home': typeof HomeRoute
  '/study': typeof StudyRouteWithChildren
  '/exam/$courseCode': typeof ExamCourseCodeRouteWithChildren
  '/results/$courseCode': typeof ResultsCourseCodeRoute
  '/session/$courseCode': typeof SessionCourseCodeRoute
  '/study/$courseCode': typeof StudyCourseCodeRoute
  '/exam/$courseCode/results': typeof ExamCourseCodeResultsRoute
  '/exam/$courseCode/session': typeof ExamCourseCodeSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/exam': typeof ExamRouteWithChildren
  '/home': typeof HomeRoute
  '/study': typeof StudyRouteWithChildren
  '/exam/$courseCode': typeof ExamCourseCodeRouteWithChildren
  '/results/$courseCode': typeof ResultsCourseCodeRoute
  '/session/$courseCode': typeof SessionCourseCodeRoute
  '/study/$courseCode': typeof StudyCourseCodeRoute
  '/exam/$courseCode/results': typeof ExamCourseCodeResultsRoute
  '/exam/$courseCode/session': typeof ExamCourseCodeSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/exam': typeof ExamRouteWithChildren
  '/home': typeof HomeRoute
  '/study': typeof StudyRouteWithChildren
  '/exam/$courseCode': typeof ExamCourseCodeRouteWithChildren
  '/results/$courseCode': typeof ResultsCourseCodeRoute
  '/session/$courseCode': typeof SessionCourseCodeRoute
  '/study/$courseCode': typeof StudyCourseCodeRoute
  '/exam/$courseCode/results': typeof ExamCourseCodeResultsRoute
  '/exam/$courseCode/session': typeof ExamCourseCodeSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/exam'
    | '/home'
    | '/study'
    | '/exam/$courseCode'
    | '/results/$courseCode'
    | '/session/$courseCode'
    | '/study/$courseCode'
    | '/exam/$courseCode/results'
    | '/exam/$courseCode/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/exam'
    | '/home'
    | '/study'
    | '/exam/$courseCode'
    | '/results/$courseCode'
    | '/session/$courseCode'
    | '/study/$courseCode'
    | '/exam/$courseCode/results'
    | '/exam/$courseCode/session'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/exam'
    | '/home'
    | '/study'
    | '/exam/$courseCode'
    | '/results/$courseCode'
    | '/session/$courseCode'
    | '/study/$courseCode'
    | '/exam/$courseCode/results'
    | '/exam/$courseCode/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ExamRoute: typeof ExamRouteWithChildren
  HomeRoute: typeof HomeRoute
  StudyRoute: typeof StudyRouteWithChildren
  ResultsCourseCodeRoute: typeof ResultsCourseCodeRoute
  SessionCourseCodeRoute: typeof SessionCourseCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$courseCode': {
      id: '/study/$courseCode'
      path: '/$courseCode'
      fullPath: '/study/$courseCode'
      preLoaderRoute: typeof StudyCourseCodeRouteImport
      parentRoute: typeof StudyRoute
    }
    '/session/$courseCode': {
      id: '/session/$courseCode'
      path: '/session/$courseCode'
      fullPath: '/session/$courseCode'
      preLoaderRoute: typeof SessionCourseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$courseCode': {
      id: '/results/$courseCode'
      path: '/results/$courseCode'
      fullPath: '/results/$courseCode'
      preLoaderRoute: typeof ResultsCourseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$courseCode': {
      id: '/exam/$courseCode'
      path: '/$courseCode'
      fullPath: '/exam/$courseCode'
      preLoaderRoute: typeof ExamCourseCodeRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/$courseCode/session': {
      id: '/exam/$courseCode/session'
      path: '/session'
      fullPath: '/exam/$courseCode/session'
      preLoaderRoute: typeof ExamCourseCodeSessionRouteImport
      parentRoute: typeof ExamCourseCodeRoute
    }
    '/exam/$courseCode/results': {
      id: '/exam/$courseCode/results'
      path: '/results'
      fullPath: '/exam/$courseCode/results'
      preLoaderRoute: typeof ExamCourseCodeResultsRouteImport
      parentRoute: typeof ExamCourseCodeRoute
    }
  }
}

interface ExamCourseCodeRouteChildren {
  ExamCourseCodeResultsRoute: typeof ExamCourseCodeResultsRoute
  ExamCourseCodeSessionRoute: typeof ExamCourseCodeSessionRoute
}

const ExamCourseCodeRouteChildren: ExamCourseCodeRouteChildren = {
  ExamCourseCodeResultsRoute: ExamCourseCodeResultsRoute,
  ExamCourseCodeSessionRoute: ExamCourseCodeSessionRoute,
}

const ExamCourseCodeRouteWithChildren = ExamCourseCodeRoute._addFileChildren(
  ExamCourseCodeRouteChildren,
)

interface ExamRouteChildren {
  ExamCourseCodeRoute: typeof ExamCourseCodeRouteWithChildren
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamCourseCodeRoute: ExamCourseCodeRouteWithChildren,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

interface StudyRouteChildren {
  StudyCourseCodeRoute: typeof StudyCourseCodeRoute
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyCourseCodeRoute: StudyCourseCodeRoute,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExamRoute: ExamRouteWithChildren,
  HomeRoute: HomeRoute,
  StudyRoute: StudyRouteWithChildren,
  ResultsCourseCodeRoute: ResultsCourseCodeRoute,
  SessionCourseCodeRoute: SessionCourseCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
